FROM golang:1.21.6-alpine3.18 as build-env

RUN apk add --update --upgrade build-base

WORKDIR /go/src

COPY . .
RUN CGO_ENABLED=0 GOOS=linux go build -ldflags="-s -w" user-service/main.go

FROM alpine

ENV PATH="$PATH:/bin/bash"

# Install ffmpeg
RUN apk add --update ffmpeg bash curl

WORKDIR /app

COPY --from=build-env /go/src/.env /app
COPY --from=build-env /go/src/bucket-credential.json /app
COPY --from=build-env /go/src/main .
RUN ls -lah

ENTRYPOINT [ "./main" ]
